version: '3'

services:

  postgrest-db:
    container_name: postgrest-db
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      # anything in initdb directory is created in the database
      - "./initdb:/docker-entrypoint-initdb.d"
